name: CI - Vérification index.html

on:
  push:
  pull_request:

jobs:
  check-index:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Vérifier que le fichier index.html existe
        run: |
          if [ ! -f index.html ]; then
            echo "❌ Le fichier index.html est manquant !"
            exit 1
          fi
          echo "✅ index.html est bien présent."
